import React, { useState, useEffect } from 'react';
import { X, Layers, Save, Loader2 } from 'lucide-react';
import { TestHistory } from '../types';
import { testApi } from '../api/test';

interface JiraSyncModalProps {
  targetItem: TestHistory;
  onClose: () => void;
  onSuccess: () => void;
}

const JiraSyncModal: React.FC<JiraSyncModalProps> = ({ targetItem, onClose, onSuccess }) => {
  const [isAssigningJira, setIsAssigningJira] = useState(false);
  const [jiraScreenshot, setJiraScreenshot] = useState<string | null>(null);
  const [jiraForm, setJiraForm] = useState({
    project: 'QONE',
    issueType: 'Bug',
    priority: 'Medium',
    summary: '',
    description: '',
    assignee: 'Unassigned'
  });

  useEffect(() => {
    prepareJiraData();
  }, [targetItem]);

  const prepareJiraData = () => {
    const item = targetItem;
    const assetName = item.scriptName;
    const platform = item.scriptOrigin || 'WEB';
    const summary = `[Bug] ${assetName} Failure on ${platform}`;

    // 1. Logs
    let logsText = "";
    if (item.logs && item.logs.length > 0) {
      const logLines = item.logs.slice(-10).map(l => `[${l.type.toUpperCase()}] ${l.msg}`).join('\n');
      logsText = `{panel:title=Execution Trace (Last 10 Lines)|titleBGColor=#F7F9F9|borderStyle=solid}\n{code:theme=RDark|linenumbers=false}\n${logLines}\n{code}\n{panel}`;
    }

    // 2. Failure Analysis
    let analysisText = "";
    if (item.failureAnalysis) {
      analysisText = "{panel:title=AI Failure Analysis|titleBGColor=#EBF5FB|borderStyle=solid}\n";
      if (item.failureAnalysis.reason) {
        analysisText += `*Root Cause:*\n${item.failureAnalysis.reason}\n\n`;
      }
      if (item.failureAnalysis.suggestion) {
        analysisText += `*Suggestion:*\n${item.failureAnalysis.suggestion}\n\n`;
      }
      if (item.failureAnalysis.thought) {
        analysisText += `*Analysis Detail:*\n${item.failureAnalysis.thought}\n`;
      }
      analysisText += "{panel}";
    }

    const description = `h2. 🚨 Test Failure Report: ${assetName}

|| Field || Details ||
| *Asset Name* | ${assetName} |
| *Platform* | ${platform} |
| *Run Date* | ${new Date(item.runDate).toLocaleString()} |
| *Trigger* | ${item.trigger.toUpperCase()} |

h3. 🔍 Failure Details
{panel:title=Error Context|titleBGColor=#FDEDEC|borderStyle=solid}
*Failure Reason:* ${item.failureReason || 'N/A'}
*AI Summary:* ${item.aiSummary || 'No summary available.'}
{panel}

${analysisText}

${logsText}

----
_Generated by Q-ONE AI Automation_`;

    // 3. Find latest screenshot from failed steps
    let screenshot = null;
    if (item.step_results) {
      const failedStep = [...item.step_results].reverse().find(s => s.status === 'failed' && s.screenshot_data);
      if (failedStep) {
        screenshot = failedStep.screenshot_data;
      }
    }

    setJiraForm({
      project: 'QONE',
      issueType: 'Bug',
      priority: 'Medium',
      summary: summary,
      description: description,
      assignee: 'Unassigned'
    });
    setJiraScreenshot(screenshot);
  };

  const handleAssignJira = async () => {
    setIsAssigningJira(true);
    try {
      await testApi.assignJira(targetItem.id);
      onSuccess();
      onClose();
    } catch (error) {
      console.error("Failed to assign Jira:", error);
      alert("Failed to assign Jira issue.");
    } finally {
      setIsAssigningJira(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-8 animate-in fade-in duration-200">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-4xl max-h-[95vh] bg-white dark:bg-[#0f1115] border border-gray-200 dark:border-gray-800 rounded-[2.5rem] shadow-2xl flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        <div className="p-6 border-b border-gray-100 dark:border-gray-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="p-3 bg-blue-100 dark:bg-blue-600/10 rounded-2xl text-blue-600 dark:text-blue-400">
              <Layers className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-lg font-black text-gray-900 dark:text-white tracking-tight uppercase">Jira Issue Registration</h3>
              <p className="text-[10px] font-bold text-gray-500 uppercase tracking-widest">Create a comprehensive ticket for tracking</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-gray-100 dark:hover:bg-gray-800 rounded-xl transition-colors">
            <X className="w-5 h-5 text-gray-400" />
          </button>
        </div>

        <div className="flex-1 overflow-hidden flex flex-col">
          <div className="flex-1 p-8 space-y-6 overflow-y-auto custom-scrollbar">
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Project</label>
                <select className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-bold transition-all focus:ring-2 focus:ring-blue-500/20" value={jiraForm.project} onChange={e => setJiraForm({ ...jiraForm, project: e.target.value })}>
                  <option value="QONE">Q-ONE Project (QONE)</option>
                  <option value="CORE">Core Infrastructure (CORE)</option>
                </select>
              </div>
              <div className="space-y-1.5">
                <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Issue Type</label>
                <select className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-bold transition-all focus:ring-2 focus:ring-blue-500/20" value={jiraForm.issueType} onChange={e => setJiraForm({ ...jiraForm, issueType: e.target.value })}>
                  <option value="Bug">Bug</option>
                  <option value="Story">Story</option>
                  <option value="Task">Task</option>
                </select>
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Summary</label>
              <input
                type="text"
                className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-bold transition-all focus:ring-2 focus:ring-blue-500/20"
                value={jiraForm.summary}
                onChange={e => setJiraForm({ ...jiraForm, summary: e.target.value })}
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Description</label>
              <textarea
                className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-medium min-h-[250px] transition-all focus:ring-2 focus:ring-blue-500/20 whitespace-pre-wrap leading-relaxed"
                value={jiraForm.description}
                onChange={e => setJiraForm({ ...jiraForm, description: e.target.value })}
              />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Assignee</label>
                <input
                  type="text"
                  className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-bold"
                  value={jiraForm.assignee}
                  readOnly
                />
              </div>
              <div className="space-y-1.5">
                <label className="text-[9px] font-black text-gray-400 uppercase tracking-widest ml-1">Priority</label>
                <select className="w-full bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl p-4 text-xs font-bold" value={jiraForm.priority} onChange={e => setJiraForm({ ...jiraForm, priority: e.target.value })}>
                  <option value="High">High</option>
                  <option value="Medium">Medium</option>
                  <option value="Low">Low</option>
                </select>
              </div>
            </div>
          </div>

          <div className="px-10 py-5 border-t border-gray-100 dark:border-gray-800 bg-gray-50/50 dark:bg-white/5 flex justify-end gap-4">
            <button
              onClick={onClose}
              className="px-6 py-3 text-[10px] font-black uppercase tracking-widest text-gray-500 hover:text-gray-900 dark:hover:text-white transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleAssignJira}
              disabled={isAssigningJira}
              className="px-8 py-2.5 bg-blue-600 hover:bg-blue-500 text-white rounded-xl text-[10px] font-black uppercase tracking-widest shadow-xl shadow-blue-600/20 transition-all flex items-center gap-2 hover:scale-[1.02] active:scale-[0.98]"
            >
              {isAssigningJira ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />}
              Assign to Jira
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default JiraSyncModal;
