"""Add steps and platform to testscript

Revision ID: 270923ef2047
Revises: 15b468928625
Create Date: 2026-02-24 14:12:52.017337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270923ef2047'
down_revision: Union[str, None] = '15b468928625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teststep_id'), table_name='teststep')
    op.drop_table('teststep')
    op.drop_index(op.f('ix_stepasset_id'), table_name='stepasset')
    op.drop_index(op.f('ix_stepasset_name'), table_name='stepasset')
    op.drop_table('stepasset')
    op.create_index(op.f('ix_testhistory_script_id'), 'testhistory', ['script_id'], unique=False)
    op.add_column('testscript', sa.Column('steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testscript', 'steps')
    op.drop_index(op.f('ix_testhistory_script_id'), table_name='testhistory')
    op.create_table('stepasset',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), server_default=sa.text("'APP'::character varying"), autoincrement=False, nullable=True),
    sa.Column('steps', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('success_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('run_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('stepasset_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stepasset_pkey'))
    )
    op.create_index(op.f('ix_stepasset_name'), 'stepasset', ['name'], unique=False)
    op.create_index(op.f('ix_stepasset_id'), 'stepasset', ['id'], unique=False)
    op.create_table('teststep',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('script_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('selector_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('selector_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('option', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('step_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('skip_on_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('screenshot', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('sleep', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('visible_if_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('visible_if', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('true_jump_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('false_jump_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['testscript.id'], name=op.f('teststep_script_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teststep_pkey'))
    )
    op.create_index(op.f('ix_teststep_id'), 'teststep', ['id'], unique=False)
    # ### end Alembic commands ###
