"""refine_knowledge_rag_schema

Revision ID: 475e9c622008
Revises: 668d131d0878
Create Date: 2026-03-23 16:29:31.403636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '475e9c622008'
down_revision: Union[str, None] = '668d131d0878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Alter knowledgedocument first
    op.alter_column('knowledgedocument', 'id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.add_column('knowledgedocument', sa.Column('sub_category', sa.String(), nullable=True))
    op.alter_column('knowledgedocument', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_knowledgedocument_depth_1'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_depth_2'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_depth_3'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_id'), table_name='knowledgedocument')
    op.drop_column('knowledgedocument', 'depth_3')
    op.drop_column('knowledgedocument', 'extracted_text')
    op.drop_column('knowledgedocument', 'parsed_data')
    op.drop_column('knowledgedocument', 'depth_1')
    op.drop_column('knowledgedocument', 'depth_2')

    # 2. Create knowledgeitem
    op.create_table('knowledgeitem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('depth_1', sa.String(), nullable=True),
    sa.Column('depth_2', sa.String(), nullable=True),
    sa.Column('depth_3', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledgedocument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgeitem_document_id'), 'knowledgeitem', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledgeitem_project_id'), 'knowledgeitem', ['project_id'], unique=False)
    
    # Ignore unrelated alterations for now to minimize failure surface
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testhistory', 'failure_analysis',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('selfhealinglog', 'modified_steps',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('selfhealinglog', 'healing_steps',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.add_column('knowledgedocument', sa.Column('depth_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledgedocument', sa.Column('depth_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('knowledgedocument', sa.Column('parsed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('knowledgedocument', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('knowledgedocument', sa.Column('depth_3', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_knowledgedocument_id'), 'knowledgedocument', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_3'), 'knowledgedocument', ['depth_3'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_2'), 'knowledgedocument', ['depth_2'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_1'), 'knowledgedocument', ['depth_1'], unique=False)
    op.alter_column('knowledgedocument', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('knowledgedocument', 'id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('knowledgedocument', 'sub_category')
    op.drop_index(op.f('ix_knowledgeitem_project_id'), table_name='knowledgeitem')
    op.drop_index(op.f('ix_knowledgeitem_document_id'), table_name='knowledgeitem')
    op.drop_table('knowledgeitem')
    # ### end Alembic commands ###
