"""add_knowledge_models

Revision ID: 668d131d0878
Revises: 340e33a7f71a
Create Date: 2026-03-23 15:45:34.708221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '668d131d0878'
down_revision: Union[str, None] = '340e33a7f71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledgedocument',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('depth_1', sa.String(), nullable=True),
    sa.Column('depth_2', sa.String(), nullable=True),
    sa.Column('depth_3', sa.String(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgedocument_category'), 'knowledgedocument', ['category'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_1'), 'knowledgedocument', ['depth_1'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_2'), 'knowledgedocument', ['depth_2'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_depth_3'), 'knowledgedocument', ['depth_3'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_id'), 'knowledgedocument', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_project_id'), 'knowledgedocument', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledgedocument_title'), 'knowledgedocument', ['title'], unique=False)
    op.create_table('knowledgemap',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('map_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledgemap_id'), 'knowledgemap', ['id'], unique=False)
    op.create_index(op.f('ix_knowledgemap_project_id'), 'knowledgemap', ['project_id'], unique=False)
    op.create_index(op.f('ix_knowledgemap_title'), 'knowledgemap', ['title'], unique=False)
    
    # Check if knowledge_documents exists before dropping
    # In some environments it might already be gone or named differently
    # But Alembic found it so let's try to drop it.
    op.drop_table('knowledge_documents')
    
    # Skip the unrelated alter_columns that were failing due to JSONB detection issues
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('depth_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('depth_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('depth_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('parsed_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_documents_pkey'))
    )
    op.drop_index(op.f('ix_knowledgemap_title'), table_name='knowledgemap')
    op.drop_index(op.f('ix_knowledgemap_project_id'), table_name='knowledgemap')
    op.drop_index(op.f('ix_knowledgemap_id'), table_name='knowledgemap')
    op.drop_table('knowledgemap')
    op.drop_index(op.f('ix_knowledgedocument_title'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_project_id'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_id'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_depth_3'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_depth_2'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_depth_1'), table_name='knowledgedocument')
    op.drop_index(op.f('ix_knowledgedocument_category'), table_name='knowledgedocument')
    op.drop_table('knowledgedocument')
    # ### end Alembic commands ###
