"""add capture_screenshots to testscript

Revision ID: 6a7c3aa3a379
Revises: 270923ef2047
Create Date: 2026-03-04 15:13:01.968669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7c3aa3a379'
down_revision: Union[str, None] = '270923ef2047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testscript', sa.Column('capture_screenshots', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testscript', 'capture_screenshots')
    # ### end Alembic commands ###
