"""Add golden_script_id to Scenario

Revision ID: 72b621315bbd
Revises: 001_initial_schema
Create Date: 2026-01-29 15:51:25.847250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72b621315bbd'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('golden_script_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scenario', 'testscript', ['golden_script_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenario', type_='foreignkey')
    op.drop_column('scenario', 'golden_script_id')
    # ### end Alembic commands ###
