"""Add PermissionMatrix table

Revision ID: da43df685017
Revises: a6ae06b94515
Create Date: 2026-03-18 16:56:13.118681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da43df685017'
down_revision: Union[str, None] = 'a6ae06b94515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissionmatrix',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('admin_allowed', sa.Boolean(), nullable=True),
    sa.Column('manager_allowed', sa.Boolean(), nullable=True),
    sa.Column('qa_engineer_allowed', sa.Boolean(), nullable=True),
    sa.Column('viewer_allowed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissionmatrix_id'), 'permissionmatrix', ['id'], unique=False)
    op.alter_column('persona', 'motivation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('persona', 'current_state',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('persona', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'::text"))
    op.alter_column('persona', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::text"))
    op.drop_column('persona', 'goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona', sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('persona', 'domain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'General'::text"))
    op.alter_column('persona', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'USER'::text"))
    op.alter_column('persona', 'current_state',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('persona', 'motivation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_permissionmatrix_id'), table_name='permissionmatrix')
    op.drop_table('permissionmatrix')
    # ### end Alembic commands ###
