"""Add Test Asset Tables

Revision ID: ea5d7de62366
Revises: 72b621315bbd
Create Date: 2026-02-10 11:48:09.197862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5d7de62366'
down_revision: Union[str, None] = '72b621315bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testaction',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('code_content', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testaction_id'), 'testaction', ['id'], unique=False)
    op.create_index(op.f('ix_testaction_name'), 'testaction', ['name'], unique=False)
    op.create_table('testdataset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('generation_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testdataset_id'), 'testdataset', ['id'], unique=False)
    op.create_index(op.f('ix_testdataset_name'), 'testdataset', ['name'], unique=False)
    op.create_table('testobject',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('selector_type', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testobject_id'), 'testobject', ['id'], unique=False)
    op.create_index(op.f('ix_testobject_name'), 'testobject', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testobject_name'), table_name='testobject')
    op.drop_index(op.f('ix_testobject_id'), table_name='testobject')
    op.drop_table('testobject')
    op.drop_index(op.f('ix_testdataset_name'), table_name='testdataset')
    op.drop_index(op.f('ix_testdataset_id'), table_name='testdataset')
    op.drop_table('testdataset')
    op.drop_index(op.f('ix_testaction_name'), table_name='testaction')
    op.drop_index(op.f('ix_testaction_id'), table_name='testaction')
    op.drop_table('testaction')
    # ### end Alembic commands ###
